[package]
name = "subxt-generated"
version = "0.1.0"
edition = "2021"

[dependencies]
# subxt = { git = "https://github.com/paritytech/subxt",  rev = "2a4da618a033bb82f768e4ef67b093b371f8b492", features = ["substrate-compat"] }
subxt = { version = "0.29.0", git = "https://github.com/paritytech/subxt", tag = "v0.29.0", default-features = false }

codec = { version = "3.0.0", package = "parity-scale-codec" }
